version: '3.5'

x-service-base: &base
  privileged: true
  image: my-db
  user: root
  environment:
    - CFG_PATH=/root/DB.config
  networks:
    - netDB

services:
  node1:
    <<: *base
    container_name: ci_node1
    privileged: true
    hostname: node1
    command: |
      /bin/bash -c "
        set -ex

        ./setup.sh node1

        sleep inf
      "
  node2:
    <<: *base
    container_name: ci_node2
    hostname: node2
    command: |
      /bin/bash -c "
        set -ex

        ./setup.sh node2

        sleep inf
      "
  node3:
    <<: *base
    container_name: ci_node3
    hostname: node3
    command: |
      /bin/bash -c "
        set -ex

        ./setup.sh node3

        sleep inf
      "
  node4:
    <<: *base
    container_name: ci_node4
    hostname: node4
    command: |
      /bin/bash -c "
        set -ex

        ./setup.sh node4

        sleep inf
      "
  node5:
    <<: *base
    container_name: ci_node5
    hostname: node5
    command: |
      /bin/bash -c "
        set -ex

        ./setup.sh node5

        sleep inf
      "
  db_tester:
    <<: *base 
    container_name: ci_tester
    hostname: tester
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5
    command: |
      /bin/bash -c "
        set -ex

        sleep 1
      "

networks:
  netDB:
    driver: bridge